# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.

# Site language
lang: ko-KR

# Site title
title: "Happy Haru's Blog"

# A description of your site for meta tag, search engine results.
description: "생명과 데이터를 잇는 연구개발자 happy-haru의 블로그입니다."

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://happy-haru.github.io"

# Favicon
favicon: images/favicon.png

# Google Analytics id
google_analytics: ""

# Site navigation
navigation:
  - text: Home
    url: /
  - text: Blog
    url: /blog/


# The shortname for your Disqus site to enable comments.
# disqus: 

# Colors
accent_color: '#2563EB' # Royal Blue requested by user

# Site footer
footer:
  content: "&copy; 2026 Happy Haru. All rights reserved."
  has_social: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/page:num/'

# Permalinks
permalink: /:year/:month/:day/:title/

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _backup
  - README.md
  - LICENSE
